#!/bin/sh
#
# test/probe-driver.sh -- the test driver that stands in for the main program,
# and the only place it is written down.
#
# Sourced, not executed. Defines two functions:
#
#   strip_subprograms SRC OUT   everything in SRC from the first `subroutine'
#                               statement onward, written to OUT. Returns 1 if
#                               the first thing left is not FCOORD, which is
#                               what says the main program and nothing else was
#                               dropped.
#   write_driver      SRC OUT   a generated main program that calls FCOORD for
#                               coordinate set 1 and NCOORD for each set after
#                               it, and dumps the per-element parameters each
#                               call left in COMMON.
#
# WHY THIS IS A FILE OF ITS OWN
#
# Both sources open with an unnamed main program, so neither can be linked
# against a test driver as it stands. Two gates need to get past that. The
# element-table gate needs it because the Lennard-Jones parameters are not
# observable in the program's output at all for any coordinate set after the
# first. The refusal gate needs it because NCOORD's `masses do not add up'
# refusal is reached only after the previous conformer's complete calculation:
# measured on this repository's smallest well-behaved fixture, driving it
# through the real binary costs 61 s on helium and 14 minutes on nitrogen,
# against milliseconds through this driver.
#
# So there are two callers, and a driver copied into both is a driver that
# drifts -- the same argument that moved the build recipe into
# test/build-flags.sh in v1.1. It is one definition here instead.
#
# The driver is generated rather than committed because one line of it differs
# between the two gases: mobcal_N2.f carries xeo in common/constants/ and
# mobcal_He.f does not, and a COMMON block declared with the wrong layout would
# silently shift every variable after the mismatch. Taking that line from the
# source file being probed means it cannot drift either.
#
# What the driver exercises is the real subroutines from the real source file.
# There is no second copy of the element table, and no second copy of any
# refusal, anywhere in it.

# Everything from the first `subroutine' statement on. The main program is the
# first program unit in both files and FCOORD is the second, so this drops
# exactly the main program. If the file is ever restructured so that some other
# subprogram comes first, this fails loudly instead of quietly compiling a
# probe with a stowaway main program in it.
strip_subprograms() {
    sed -n '/^      subroutine /,$p' "$1" > "$2"
    if ! head -1 "$2" | grep -q '^      subroutine fcoord('; then
        echo "    expected the first remaining line to be subroutine fcoord," >&2
        echo "    got: $(head -1 "$2")" >&2
        return 1
    fi
    return 0
}

write_driver() {
    src=$1
    out=$2
    # The continuation line of common/constants/, lifted from the source under
    # test rather than restated here.
    constants=$(sed -n '/^      common\/constants\/mu,ro,eo,pi,cang/{
                            n
                            p
                            q
                        }' "$src")
    [ -n "$constants" ] || {
        echo "probe-driver.sh: cannot read common/constants/ from $src" >&2
        return 1
    }
    {
        cat <<'PROLOGUE'
c
c     ljprobe -- generated by test/probe-driver.sh; not part of the program.
c
c     Stands in for the main program so that FCOORD and NCOORD can be called
c     directly, and writes out the per-element parameters each call left in
c     COMMON. Unit 7 is the probe's data file, unit 8 is the output file the
c     two subroutines expect to be open.
c
      implicit double precision (a-h,m-z)
      include 'mobcal_limits.inc'
      character*30 filen1,unit,dchar,xlabel
      common/printswitch/ip,it,iu1,iu2,iu3,iv,im2,im4,igs
      common/constants/mu,ro,eo,pi,cang,ro2,dipol,emax,m1,m2,
PROLOGUE
        echo "$constants"
        cat <<'BODY'
      common/xrandom/i1,i2,i3,i4,i5,i6
c
      open(20,file='mobcal.in')
      read(20,'(a30)') filen1
      close (20)
c
      ip=0
      it=0
      iu1=0
      iu2=0
      iu3=0
      iv=0
      im2=0
      im4=0
      igs=0
c
      pi=3.14159265358979323846d0
      cang=180.d0/pi
      xe=1.60217733d-19
      xk=1.380658d-23
      xn=6.0221367d23
c
      open (8,file='ljprobe.out')
      open (7,file='ljprobe.dat')
c
      call fcoord(filen1,unit,dchar,xlabel,asymp)
      iic=1
      call ljdump(1)
      do 1000 ic=2,icoord
      iic=ic
      call ncoord(unit,dchar,asymp)
      call ljdump(ic)
 1000 continue
c
      close (7)
      close (8)
      stop
      end
c
c     ***************************************************************
c
      subroutine ljdump(ic)
c
c     One record per atom: coordinate set, atom index, then the three
c     quantities the element table sets that live in COMMON -- the LJ well
c     depth in eV, the LJ radius in angstroms, and the hard-sphere radius in
c     angstroms.
c
      implicit double precision (a-h,m-z)
      include 'mobcal_limits.inc'
      common/constants/mu,ro,eo,pi,cang,ro2,dipol,emax,m1,m2,
BODY
        echo "$constants"
        cat <<'EPILOGUE'
      common/ljparameters/eolj(len),rolj(len),eox4(len),
     ?ro6lj(len),ro12lj(len),dro6(len),dro12(len)
      common/hsparameters/rhs(len),rhs2(len)
c
      do 1000 iatom=1,inatom
 1000 write(7,600) ic,iatom,eolj(iatom)/xe,rolj(iatom)*1.0d10,
     ?rhs(iatom)*1.0d10
  600 format(i5,i5,3(1x,1pe22.15))
c
      return
      end
EPILOGUE
    } > "$out"
}
